import { WearableDevice } from './types';

export const SUPPORTED_DEVICES: WearableDevice[] = [
    {
        id: 'apple-health',
        name: 'Apple Health',
        manufacturer: 'Apple',
        model: 'HealthKit Bridge',
        logo: '🍎',
        connectionType: 'Mobile Bridge',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Steps', 'Sleep', 'Heart Rate', 'HRV', 'Calories', 'Workouts', 'Weight'],
        permissions: { Sleep: true, Steps: true, HRV: true, Workouts: true },
        syncFrequency: 'Manual',
        priorityOrder: 1
    },
    {
        id: 'oura-ring',
        name: 'Oura Ring',
        manufacturer: 'Oura',
        model: 'Gen 3 Heritage',
        logo: '💍',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Sleep', 'HRV', 'Body Temperature', 'Recovery', 'Respiration Rate', 'Resting HR'],
        permissions: { Sleep: true, HRV: true, Recovery: true },
        syncFrequency: '30m',
        priorityOrder: 2
    },
    {
        id: 'whoop-strap',
        name: 'WHOOP Strap',
        manufacturer: 'WHOOP',
        model: 'Strap 4.0',
        logo: '⚡',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['HRV', 'Recovery', 'Stress', 'Sleep', 'Heart Rate', 'Respiration Rate'],
        permissions: { HRV: true, Recovery: true, Stress: true },
        syncFrequency: '15m',
        priorityOrder: 3
    },
    {
        id: 'garmin-connect',
        name: 'Garmin Connect',
        manufacturer: 'Garmin',
        model: 'Fenix 7 Solar',
        logo: '🏃',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Workouts', 'Steps', 'Calories', 'Heart Rate', 'HRV', 'Blood Oxygen', 'Stress'],
        permissions: { Workouts: true, Steps: true, Calories: true },
        syncFrequency: 'Daily',
        priorityOrder: 4
    },
    {
        id: 'fitbit',
        name: 'Fitbit',
        manufacturer: 'Google/Fitbit',
        model: 'Sense 2',
        logo: '🔷',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Steps', 'Sleep', 'Calories', 'Heart Rate', 'Resting HR'],
        permissions: { Steps: true, Sleep: true },
        syncFrequency: '1h',
        priorityOrder: 5
    },
    {
        id: 'polar-ble',
        name: 'Polar H10 Sensor',
        manufacturer: 'Polar',
        model: 'H10 Chest Strap',
        logo: '❄',
        connectionType: 'BLE',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Heart Rate', 'HRV', 'Workouts'],
        permissions: { 'Heart Rate': true, HRV: true },
        syncFrequency: 'Manual',
        priorityOrder: 6
    },
    {
        id: 'google-health-connect',
        name: 'Health Connect',
        manufacturer: 'Google',
        model: 'Android Bridge',
        logo: '🤖',
        connectionType: 'Mobile Bridge',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Steps', 'Sleep', 'Calories', 'Workouts'],
        permissions: { Steps: true, Sleep: true },
        syncFrequency: 'Manual',
        priorityOrder: 7
    },
    {
        id: 'google-fit',
        name: 'Google Fit',
        manufacturer: 'Google',
        model: 'Cloud Sync',
        logo: '📊',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Steps', 'Calories', 'Workouts'],
        permissions: { Steps: true },
        syncFrequency: 'Daily',
        priorityOrder: 8
    },
    {
        id: 'strava',
        name: 'Strava',
        manufacturer: 'Strava',
        model: 'Athletes Club',
        logo: '🚲',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Workouts', 'Heart Rate'],
        permissions: { Workouts: true },
        syncFrequency: 'Manual',
        priorityOrder: 9
    },
    {
        id: 'dexcom',
        name: 'Dexcom CGM',
        manufacturer: 'Dexcom',
        model: 'G6 Continuous Glucose',
        logo: '💉',
        connectionType: 'Cloud API',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Biomarkers'],
        permissions: { Biomarkers: true },
        syncFrequency: '15m',
        priorityOrder: 10
    },
    {
        id: 'generic-ble-hr',
        name: 'Generic BLE Monitor',
        manufacturer: 'Generic Sensor',
        model: 'Standard Bluetooth HR',
        logo: '❤',
        connectionType: 'BLE',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Heart Rate', 'Battery'],
        permissions: { 'Heart Rate': true },
        syncFrequency: 'Manual',
        priorityOrder: 11
    },
    {
        id: 'device-simulator',
        name: 'SuppSync Simulator',
        manufacturer: 'SuppSync Corp',
        model: 'Universal Health Sim',
        logo: '🤖',
        connectionType: 'Simulator',
        connectionStatus: 'Disconnected',
        healthState: 'Offline',
        supportedMetrics: ['Heart Rate', 'HRV', 'Sleep', 'Recovery', 'Stress', 'Calories', 'Steps', 'Body Temperature', 'Blood Oxygen'],
        permissions: { 'Heart Rate': true, HRV: true, Sleep: true, Recovery: true },
        syncFrequency: '15m',
        priorityOrder: 12
    }
];

export const getDeviceCatalog = (): WearableDevice[] => {
    return [...SUPPORTED_DEVICES];
};
